baseURL: https://joaobugelli.com/
languageCode: pt-br
defaultContentLanguage: pt
title: Jo√£o Bugelli

module:
  imports:
    - path: github.com/imfing/hextra

outputs:
  home: [HTML,RSS]


markup:
  # allow raw html
  goldmark:
    renderer:
      unsafe: true

  # enable math support
    extensions:
      passthrough:
        delimiters:
          block: [['\[', '\]'], ["$$", "$$"]]
          inline: [['\(', '\)']]
        enable: true

  # enable hextra syntax highlight
  highlight:
    noClasses: false

permalinks:
  blog: "/blog/:slug/"

